# Generated by Django 6.0.4 on 2026-04-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField()),
                ('OrderDate', models.DateTimeField(auto_now_add=True)),
                ('ItemName', models.CharField(max_length=200)),
                ('OrderQty', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DeliveryAddress', models.CharField(max_length=300)),
            ],
        ),
    ]
